- hosts: all
  tasks:
  - name: restart server
    become: true
    shell: sleep 5 && shutdown -r now "Ansible updates triggered"
    async: 1
    poll: 0
  - name: 'waiting for server to return...'
    become: false
    local_action: 'wait_for host={{ ansible_ssh_host }} state=started port=22 delay=30 timeout=300 connect_timeout=15'
